setOption("ScaleConversions", true);
run("8-bit");
selectImage("Cell1_647_1.tif");
setOption("ScaleConversions", true);
run("8-bit");
selectImage("Cell1_488_1.tif");
run("Green");
selectImage("Cell1_647_1.tif");
run("Magenta");
run("Merge Channels...", "c2=Cell1_488_1.tif c6=Cell1_647_1.tif create keep");
run("Flatten");
run("Images to Stack", "use keep");
run("Make Montage...", "columns=3 rows=1 scale=0.25 label");
